In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
!pip install -q --upgrade transformers datasets peft bitsandbytes trl
!pip install -q accelerate

In [3]:
from accelerate.utils import write_basic_config
write_basic_config()

PosixPath('/root/.cache/huggingface/accelerate/default_config.yaml')

In [4]:
import os
import torch
import numpy as np
import pandas as pd
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    AutoConfig
)
from datasets import load_dataset, concatenate_datasets
from huggingface_hub import login
from peft import LoraConfig, get_peft_model,PeftModel
from trl import SFTTrainer
import transformers
from torch.utils.data import DataLoader
from tqdm import tqdm  # For progress bar

In [5]:
seed = 7
torch.manual_seed(seed)
np.random.seed(seed)

In [6]:
print(f"Number of GPUs Available:{torch.cuda.device_count()}")

Number of GPUs Available:2

In [7]:
token = ""
login(token)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful

In [8]:
save_dir = "/kaggle/working"
model_id = "meta-llama/Llama-3.2-1B-Instruct"

In [9]:
lora_config = {"lora_config1" : LoraConfig(
    r=256,
    lora_alpha=512,
    lora_dropout=0.2,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bias="none",
    task_type="CAUSAL_LM",
),
 "lora_config2" : LoraConfig(
    r=128,
    lora_alpha=256,
    lora_dropout=0.2,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bias="none",
    task_type="CAUSAL_LM",
),
 "lora_config3" : LoraConfig(
    r=64,
    lora_alpha=128,
    lora_dropout=0.2,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bias="none",
    task_type="CAUSAL_LM",
),
 "lora_config4" : LoraConfig(
    r=32,
    lora_alpha=64,
    lora_dropout=0.2,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bias="none",
    task_type="CAUSAL_LM",
),
 "lora_config5" : LoraConfig(
    r=32,
    lora_alpha=64,
    lora_dropout=0.2,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bias="none",
    task_type="CAUSAL_LM",
)
}

In [10]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=torch.float16
)

In [11]:
tokenizer = AutoTokenizer.from_pretrained(model_id, token=token)
tokenizer.padding_side = 'left'

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

In [12]:
# Define default tokens
DEFAULT_PAD_TOKEN = "[PAD]"
DEFAULT_EOS_TOKEN = "</s>"
DEFAULT_BOS_TOKEN = "<s>"

special_tokens_dict = {}
if tokenizer.pad_token is None:
    special_tokens_dict['pad_token'] = DEFAULT_PAD_TOKEN
if tokenizer.eos_token is None:
    special_tokens_dict['eos_token'] = DEFAULT_EOS_TOKEN
if tokenizer.bos_token is None:
    special_tokens_dict['bos_token'] = DEFAULT_BOS_TOKEN

if special_tokens_dict:
    tokenizer.add_special_tokens(special_tokens_dict)

In [13]:
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    token=token
)

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [14]:
def preprocess_function(examples):
    inputs = [
        f"<|begin_of_text|><|start_header_id|>system <|end_header_id|>"
        "You are an expert math assistant<|eot_id|><|start_header_id|>user <|end_header_id|>"
        f"Solve the following math problem: {problem}\n"
        "Show all intermediate steps and please mandatorily include the final answer in LaTeX format in a box like \\boxed{{}}."
        "<|eot_id|><|start_header_id|> assistant <|end_header_id|>"for problem in examples['problem']
    ]
    # Append the solution with EOS token
    targets = [
        f"{solution}{tokenizer.eos_token}"
        for solution in examples['solution']
    ]
    # Concatenate inputs and targets
    full_texts = [inp + tgt for inp, tgt in zip(inputs, targets)]
    # Tokenize the concatenated texts
    model_inputs = tokenizer(
        full_texts,
        max_length=512,
        truncation=True,
        padding="longest",  # Use dynamic padding
        return_tensors="pt"
    )
    # Create labels by cloning input IDs
    labels = model_inputs["input_ids"].clone()

    # Mask input tokens in labels
    for i in range(len(labels)):
        input_ids = tokenizer(inputs[i], add_special_tokens=False).input_ids
        input_len = len(input_ids)
        labels[i][:input_len] = -100  # Mask the input tokens
    model_inputs["labels"] = labels
    return model_inputs

In [15]:
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,  # For causal language modeling
    pad_to_multiple_of=8  # For faster GPU performance
)

In [16]:
dataset = load_dataset("lighteval/MATH",trust_remote_code=True)
dataset['train'] = dataset['train'].filter(
        lambda x: x['level'] != f"Level ?"
    )

MATH.py:   0%|          | 0.00/4.10k [00:00<?, ?B/s]

data/algebra_train.jsonl:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

(…)ata/counting_and_probability_train.jsonl:   0%|          | 0.00/707k [00:00<?, ?B/s]

data/geometry_train.jsonl:   0%|          | 0.00/1.15M [00:00<?, ?B/s]

data/intermediate_algebra_train.jsonl:   0%|          | 0.00/1.25M [00:00<?, ?B/s]

data/number_theory_train.jsonl:   0%|          | 0.00/639k [00:00<?, ?B/s]

data/prealgebra_train.jsonl:   0%|          | 0.00/778k [00:00<?, ?B/s]

data/precalculus_train.jsonl:   0%|          | 0.00/903k [00:00<?, ?B/s]

data/algebra_test.jsonl:   0%|          | 0.00/706k [00:00<?, ?B/s]

data/counting_and_probability_test.jsonl:   0%|          | 0.00/377k [00:00<?, ?B/s]

data/geometry_test.jsonl:   0%|          | 0.00/562k [00:00<?, ?B/s]

data/intermediate_algebra_test.jsonl:   0%|          | 0.00/860k [00:00<?, ?B/s]

data/number_theory_test.jsonl:   0%|          | 0.00/376k [00:00<?, ?B/s]

data/prealgebra_test.jsonl:   0%|          | 0.00/553k [00:00<?, ?B/s]

data/precalculus_test.jsonl:   0%|          | 0.00/614k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/7500 [00:00<?, ? examples/s]

In [17]:
for lci in lora_config.keys():
    model.resize_token_embeddings(len(tokenizer))
    model = get_peft_model(model, lora_config[lci])
    trainable_params = 0
    total_params = 0
    for param in model.parameters():
        num_params = param.numel()
        total_params += num_params
        if param.requires_grad:
            trainable_params += num_params
    print(f"Trainable parameters: {trainable_params} ({100 * trainable_params / total_params:.2f}% of total), Total : {total_params}")

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

Trainable parameters: 180355072 (19.40% of total), Total : 929632256

Trainable parameters: 90177536 (10.74% of total), Total : 839454720

Trainable parameters: 45088768 (5.68% of total), Total : 794365952

Trainable parameters: 22544384 (2.92% of total), Total : 771821568

Trainable parameters: 22544384 (2.92% of total), Total : 771821568

In [18]:
for level in range(1, 6):
    print(f"\nStarting training for Level {level}")

    if level == 1:
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=bnb_config,
            device_map="auto",
            token=token,
        )
        model.resize_token_embeddings(len(tokenizer))
        lc = lora_config["lora_config1"]
        model = get_peft_model(model, lc)

    else:
        # Load tokenizer and model from previous level
        prev_level = level - 1
        prev_model_path = os.path.join(save_dir, f"rank_llama_level_{prev_level}")
        
        model = PeftModel.from_pretrained(
        model=model,
        model_id = prev_model_path,
        peft_config=bnb_config,
        device_map="auto")
        
        model.resize_token_embeddings(len(tokenizer))
        if level == 2:
            lc = lora_config["lora_config2"]
            model = get_peft_model(model, lc)
        if level == 3:
            lc = lora_config["lora_config3"]
            model = get_peft_model(model, lc)
        if level == 4:
            lc = lora_config["lora_config4"]
            model = get_peft_model(model, lc)
        if level == 5:
            lc = lora_config["lora_config5"]
            model = get_peft_model(model, lc)       
        tokenizer.padding_side = "left"
    
    # Filter the dataset by current level
    level_train = dataset['train'].filter(
        lambda x: x['level'] <= f"Level {level}"
    )
    level_test = dataset['test'].filter(
        lambda x: x['level'] <= f"Level {level}"
    )
    
    print(f"Number of training samples: {len(level_train)}")
    print(f"Number of test samples: {len(level_test)}")
    
#     # Combine with previous levels' data if applicable
#     if level > 1:
#         replay_fraction = 0.1  # Adjust as needed
#         previous_levels_train = dataset['train'].filter(
#             lambda x: int(x['level'].split()[-1]) < level
#         ).shuffle(seed).select(range(int(len(level_train)*replay_fraction)))
#         level_train = concatenate_datasets([level_train, previous_levels_train])
    
    # Tokenize datasets
    level_train = level_train.map(preprocess_function, batched=True)
    level_test = level_test.map(preprocess_function, batched=True)
    
#     level_train = level_train.select(range(5))
#     level_test = level_test.select(range(2))
    
    training_args = TrainingArguments(
      output_dir=os.path.join(save_dir, f"rank_level_overall"),
      per_device_train_batch_size=4,
      gradient_accumulation_steps=2,
      warmup_ratio=0.1,
      num_train_epochs=5,
      learning_rate=5e-5,
      fp16=True,  # Use bf16 precision
      logging_steps=10,
      optim="paged_adamw_8bit",
      evaluation_strategy="steps",
      eval_steps=50,
      save_steps=100,
      save_total_limit=2,
      report_to="none",  # Change to "wandb" if using Weights & Biases
      run_name=f"llama_FineTuning_Level_overall",
        ddp_find_unused_parameters=False,
    )
    
    # Initialize the trainer
    trainer = SFTTrainer(
        model=model,
        train_dataset=level_train,
        eval_dataset=level_test,
        peft_config=lc,
        args=training_args,
        data_collator=data_collator,
    )
    
    # Train the model
    trainer.train()

    
    # Save the model
    model_save_path = os.path.join(save_dir, f"rank_llama_level_{level}")
    model.save_pretrained(model_save_path,save_embedding_layers=True)
    tokenizer.save_pretrained(model_save_path)
    
    # Evaluate the model
    results = trainer.evaluate()
    print(f"Overall evaluation results: {results}")
    
    print(trainer.state.log_history)
    print("Evaluating:")
    if level == 5:
        model.eval()  # Set model to evaluation mode
        
        test_samples = []
        for idx in range(len(level_test)):
            sample = level_test[idx]
            input_text = (
                f"<|begin_of_text|><|start_header_id|>system <|end_header_id|>"
                "You are an expert math assistant<|eot_id|><|start_header_id|>user <|end_header_id|>"
                f"Solve the following math problem: {sample['problem']}\n"
                "Show all intermediate steps and please mandatorily include the final answer in LaTeX format in a box like \\boxed{{}}."
                "<|eot_id|><|start_header_id|> assistant <|end_header_id|>"
            )
            test_samples.append({
                "input_text": input_text,
                "problem": sample['problem'],
                "level": sample['level'],
                "type": sample['type'],
                "ground_truth": sample['solution']
            })
            
        def collate_fn(batch):
            input_texts = [sample['input_text'] for sample in batch]
            model_inputs = tokenizer(
                input_texts,
                padding=True,
                truncation=True,
                max_length=1024,  # Adjust as needed
                return_tensors="pt"
            )
            model_inputs = {k: v.to(model.device) for k, v in model_inputs.items()}
            return model_inputs, batch
    
        batch_size = 32  # Adjust based on your GPU memory
        test_dataloader = DataLoader(test_samples, batch_size=batch_size, collate_fn=collate_fn)
    
        results_list = []
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
        for batch_idx, (model_inputs, batch_samples) in enumerate(tqdm(test_dataloader, desc=f"Evaluating Level {level}")):
            current_batch_size = model_inputs['input_ids'].size(0)
            # Generate predictions
            try:
                with torch.no_grad():
                    output_ids = model.generate(
                        input_ids=model_inputs['input_ids'],
                        attention_mask=model_inputs['attention_mask'],
                        max_new_tokens=512,  
                        do_sample=False,
                        eos_token_id=tokenizer.eos_token_id,
                        pad_token_id=tokenizer.pad_token_id
                    )
                # Decode the outputs
                for i in range(current_batch_size):
                    predicted_text = tokenizer.decode(output_ids[i], skip_special_tokens=True)
                    # Store the results
                    results_list.append({
                        "problem": batch_samples[i]['problem'],
                        "level": batch_samples[i]['level'],
                        "type": batch_samples[i]['type'],
                        "ground_truth": batch_samples[i]['ground_truth'],
                        "predicted_solution": predicted_text
                    })
            except Exception as e:
                print(f"Error during generation at batch {batch_idx+1}: {e}")
                # In case of error, record empty predictions for this batch
                for i in range(current_batch_size):
                    results_list.append({
                        "problem": batch_samples[i]['problem'],
                        "level": batch_samples[i]['level'],
                        "type": batch_samples[i]['type'],
                        "ground_truth": batch_samples[i]['ground_truth'],
                        "predicted_solution": ""  # Empty string for predicted_text
                    })
                continue  # Proceed to the next batch
    
            # Optionally, save intermediate results every N batches
            if (batch_idx + 1) % 100 == 0:
                results_df = pd.DataFrame(results_list)
                results_save_path = os.path.join(save_dir, f"test_results_level_{level}_batch_{batch_idx+1}.csv")
                results_df.to_csv(results_save_path, index=False)
                print(f"Saved test results up to batch {batch_idx+1} to {results_save_path}")
        
        
        results_df = pd.DataFrame(results_list)
        results_save_path = os.path.join(save_dir, f"test_results_level_{level}.csv")
        results_df.to_csv(results_save_path, index=False)
        print(f"Saved test results to {results_save_path}")

Starting training for Level 1

Filter:   0%|          | 0/7498 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

Number of training samples: 564
Number of test samples: 437

Map:   0%|          | 0/564 [00:00<?, ? examples/s]

Map:   0%|          | 0/437 [00:00<?, ? examples/s]

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:309: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:494: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py:257: UserWarning: Setting `save_embedding_layers` to `True` as the embedding layer has been resized during finetuning.
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py:257: UserWarning: Setting `save_embedding_layers` to `True` as the embedding layer has been resized during finetuning.
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py:257: UserWarning: Setting `save_embedding_layers` to `True` as the embedding layer has been resized during finetuning.
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py:257: UserWarning: Setting `save_embedding_layers` to `True` as the embedding layer has been resized during finetuning.
  warnings.warn(

Overall evaluation results: {'eval_loss': 0.9998300075531006, 'eval_runtime': 50.2805, 'eval_samples_per_second': 8.691, 'eval_steps_per_second': 1.094, 'epoch': 4.964539007092198}
[{'loss': 2.3582, 'grad_norm': 5.860780239105225, 'learning_rate': 1.4285714285714285e-05, 'epoch': 0.14184397163120568, 'step': 10}, {'loss': 1.0965, 'grad_norm': 2.1129419803619385, 'learning_rate': 2.857142857142857e-05, 'epoch': 0.28368794326241137, 'step': 20}, {'loss': 0.8597, 'grad_norm': 2.007134437561035, 'learning_rate': 4.2857142857142856e-05, 'epoch': 0.425531914893617, 'step': 30}, {'loss': 0.8599, 'grad_norm': 2.6783788204193115, 'learning_rate': 4.9206349206349204e-05, 'epoch': 0.5673758865248227, 'step': 40}, {'loss': 0.7174, 'grad_norm': 2.219571352005005, 'learning_rate': 4.761904761904762e-05, 'epoch': 0.7092198581560284, 'step': 50}, {'eval_loss': 0.7026652693748474, 'eval_runtime': 46.0735, 'eval_samples_per_second': 9.485, 'eval_steps_per_second': 1.194, 'epoch': 0.7092198581560284, 'step': 50}, {'loss': 0.6688, 'grad_norm': 1.891318917274475, 'learning_rate': 4.603174603174603e-05, 'epoch': 0.851063829787234, 'step': 60}, {'loss': 0.733, 'grad_norm': 1.739607810974121, 'learning_rate': 4.4444444444444447e-05, 'epoch': 0.9929078014184397, 'step': 70}, {'loss': 0.5472, 'grad_norm': 1.7802876234054565, 'learning_rate': 4.2857142857142856e-05, 'epoch': 1.1347517730496455, 'step': 80}, {'loss': 0.5343, 'grad_norm': 1.5266164541244507, 'learning_rate': 4.126984126984127e-05, 'epoch': 1.2765957446808511, 'step': 90}, {'loss': 0.4932, 'grad_norm': 1.6483763456344604, 'learning_rate': 3.968253968253968e-05, 'epoch': 1.4184397163120568, 'step': 100}, {'eval_loss': 0.6935751438140869, 'eval_runtime': 49.205, 'eval_samples_per_second': 8.881, 'eval_steps_per_second': 1.118, 'epoch': 1.4184397163120568, 'step': 100}, {'loss': 0.445, 'grad_norm': 1.7081114053726196, 'learning_rate': 3.809523809523809e-05, 'epoch': 1.5602836879432624, 'step': 110}, {'loss': 0.4458, 'grad_norm': 1.8405543565750122, 'learning_rate': 3.650793650793651e-05, 'epoch': 1.702127659574468, 'step': 120}, {'loss': 0.4834, 'grad_norm': 2.0248937606811523, 'learning_rate': 3.492063492063492e-05, 'epoch': 1.8439716312056738, 'step': 130}, {'loss': 0.4669, 'grad_norm': 1.6581966876983643, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.9858156028368794, 'step': 140}, {'loss': 0.3603, 'grad_norm': 1.8547756671905518, 'learning_rate': 3.1746031746031745e-05, 'epoch': 2.127659574468085, 'step': 150}, {'eval_loss': 0.7950767874717712, 'eval_runtime': 50.2497, 'eval_samples_per_second': 8.697, 'eval_steps_per_second': 1.095, 'epoch': 2.127659574468085, 'step': 150}, {'loss': 0.2657, 'grad_norm': 1.853538155555725, 'learning_rate': 3.0158730158730158e-05, 'epoch': 2.269503546099291, 'step': 160}, {'loss': 0.274, 'grad_norm': 1.7783176898956299, 'learning_rate': 2.857142857142857e-05, 'epoch': 2.4113475177304964, 'step': 170}, {'loss': 0.2699, 'grad_norm': 1.9083243608474731, 'learning_rate': 2.6984126984126984e-05, 'epoch': 2.5531914893617023, 'step': 180}, {'loss': 0.2544, 'grad_norm': 1.7290642261505127, 'learning_rate': 2.5396825396825397e-05, 'epoch': 2.6950354609929077, 'step': 190}, {'loss': 0.2534, 'grad_norm': 1.8686301708221436, 'learning_rate': 2.380952380952381e-05, 'epoch': 2.8368794326241136, 'step': 200}, {'eval_loss': 0.7635766267776489, 'eval_runtime': 49.96, 'eval_samples_per_second': 8.747, 'eval_steps_per_second': 1.101, 'epoch': 2.8368794326241136, 'step': 200}, {'loss': 0.3021, 'grad_norm': 2.7363696098327637, 'learning_rate': 2.2222222222222223e-05, 'epoch': 2.978723404255319, 'step': 210}, {'loss': 0.195, 'grad_norm': 1.654327630996704, 'learning_rate': 2.0634920634920636e-05, 'epoch': 3.120567375886525, 'step': 220}, {'loss': 0.1574, 'grad_norm': 3.893305540084839, 'learning_rate': 1.9047619047619046e-05, 'epoch': 3.2624113475177303, 'step': 230}, {'loss': 0.1459, 'grad_norm': 2.5107829570770264, 'learning_rate': 1.746031746031746e-05, 'epoch': 3.404255319148936, 'step': 240}, {'loss': 0.1469, 'grad_norm': 1.7558128833770752, 'learning_rate': 1.5873015873015872e-05, 'epoch': 3.546099290780142, 'step': 250}, {'eval_loss': 0.8747156262397766, 'eval_runtime': 50.1778, 'eval_samples_per_second': 8.709, 'eval_steps_per_second': 1.096, 'epoch': 3.546099290780142, 'step': 250}, {'loss': 0.1496, 'grad_norm': 1.7437101602554321, 'learning_rate': 1.4285714285714285e-05, 'epoch': 3.6879432624113475, 'step': 260}, {'loss': 0.1338, 'grad_norm': 1.630589246749878, 'learning_rate': 1.2698412698412699e-05, 'epoch': 3.829787234042553, 'step': 270}, {'loss': 0.1368, 'grad_norm': 1.8043439388275146, 'learning_rate': 1.1111111111111112e-05, 'epoch': 3.971631205673759, 'step': 280}, {'loss': 0.1311, 'grad_norm': 1.0200833082199097, 'learning_rate': 9.523809523809523e-06, 'epoch': 4.113475177304965, 'step': 290}, {'loss': 0.0847, 'grad_norm': 1.9639800786972046, 'learning_rate': 7.936507936507936e-06, 'epoch': 4.25531914893617, 'step': 300}, {'eval_loss': 1.0173354148864746, 'eval_runtime': 50.1474, 'eval_samples_per_second': 8.714, 'eval_steps_per_second': 1.097, 'epoch': 4.25531914893617, 'step': 300}, {'loss': 0.0812, 'grad_norm': 1.0392966270446777, 'learning_rate': 6.349206349206349e-06, 'epoch': 4.397163120567376, 'step': 310}, {'loss': 0.0851, 'grad_norm': 1.6045151948928833, 'learning_rate': 4.7619047619047615e-06, 'epoch': 4.539007092198582, 'step': 320}, {'loss': 0.0955, 'grad_norm': 1.7148793935775757, 'learning_rate': 3.1746031746031746e-06, 'epoch': 4.680851063829787, 'step': 330}, {'loss': 0.0915, 'grad_norm': 0.8579506874084473, 'learning_rate': 1.5873015873015873e-06, 'epoch': 4.822695035460993, 'step': 340}, {'loss': 0.099, 'grad_norm': 1.4350996017456055, 'learning_rate': 0.0, 'epoch': 4.964539007092198, 'step': 350}, {'eval_loss': 0.9998300075531006, 'eval_runtime': 49.9413, 'eval_samples_per_second': 8.75, 'eval_steps_per_second': 1.101, 'epoch': 4.964539007092198, 'step': 350}, {'train_runtime': 1082.507, 'train_samples_per_second': 2.605, 'train_steps_per_second': 0.323, 'total_flos': 9921955784294400.0, 'train_loss': 0.4120777206761496, 'epoch': 4.964539007092198, 'step': 350}, {'eval_loss': 0.9998300075531006, 'eval_runtime': 50.2805, 'eval_samples_per_second': 8.691, 'eval_steps_per_second': 1.094, 'epoch': 4.964539007092198, 'step': 350}]
Evaluating:

Starting training for Level 2

Filter:   0%|          | 0/7498 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

Number of training samples: 1912
Number of test samples: 1331

Map:   0%|          | 0/1912 [00:00<?, ? examples/s]

Map:   0%|          | 0/1331 [00:00<?, ? examples/s]

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:309: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:494: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

Overall evaluation results: {'eval_loss': 0.9355211853981018, 'eval_runtime': 147.334, 'eval_samples_per_second': 9.034, 'eval_steps_per_second': 1.133, 'epoch': 5.0}

Filter:   0%|          | 0/7498 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

Number of training samples: 3504
Number of test samples: 2462

Map:   0%|          | 0/3504 [00:00<?, ? examples/s]

Map:   0%|          | 0/2462 [00:00<?, ? examples/s]

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:309: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:494: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

Overall evaluation results: {'eval_loss': 0.8119277358055115, 'eval_runtime': 268.9486, 'eval_samples_per_second': 9.154, 'eval_steps_per_second': 1.145, 'epoch': 5.0}

Filter:   0%|          | 0/7498 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

Number of training samples: 5194
Number of test samples: 3676

Map:   0%|          | 0/5194 [00:00<?, ? examples/s]

Map:   0%|          | 0/3676 [00:00<?, ? examples/s]

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:309: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:494: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)